services:
  frontend:
    build:
      context: what-surv-frontend
    ports:
      - "5173:5173"
    volumes:
      - app_dist:/usr/app/frontend/dist
  
  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - app_dist:/srv
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/caddy_config
    restart: unless-stopped
    depends_on:
      - backend
      - frontend

  backend:
    build:
      context: what-surv-backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - ./what-surv-backend/.env
    environment:
      - DB_HOST=db

  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - ./what-surv-backend/.env

volumes:
  db-data:
  caddy_data:
  caddy_config:
  app_dist:
