services:
  # frontend:
  #   build:
  #     context: what-surv-frontend
  #   ports:
  #     - "5173:5173"

  backend:
    build:
      context: what-surv-backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - ./what-surv-backend/.env
    environment:
      - DB_HOST=db

  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - ./what-surv-backend/.env

  caddy:
    image: caddy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

# register named volumes
volumes:
  db-data:
  caddy_data:
  caddy_config:
